name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv venv.venv/bin/activate
        sudo pip install pipenv
        pipenv install
    - name: Test 
      run: |
        pipenv shell
        python3 -m unittest test.py
   
